/**
 * ClarifyingChat — interactive Q&A for refining podcast topic.
 * Shows questions one at a time, collects answers.
 * Props:
 *   - questions: string[] — generated by Edge Function
 *   - onComplete: (answers) => void — called when all questions answered
 *   - onCancel: () => void
 */
import { useState } from "react";
import { View, Text, TextInput, TouchableOpacity, StyleSheet } from "react-native";

interface Props {
  questions: string[];
  onComplete: (answers: Array<{ q: string; a: string }>) => void;
  onCancel: () => void;
}

export function ClarifyingChat({ questions, onComplete, onCancel }: Props) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answer, setAnswer] = useState("");
  const [answers, setAnswers] = useState<Array<{ q: string; a: string }>>([]);

  const handleNext = () => {
    if (!answer.trim()) return;
    const newAnswers = [...answers, { q: questions[currentIndex], a: answer.trim() }];

    if (currentIndex < questions.length - 1) {
      setAnswers(newAnswers);
      setCurrentIndex(currentIndex + 1);
      setAnswer("");
    } else {
      onComplete(newAnswers);
    }
  };

  const isLast = currentIndex === questions.length - 1;

  return (
    <View style={styles.container}>
      <Text style={styles.progress}>
        Question {currentIndex + 1} of {questions.length}
      </Text>
      <Text style={styles.question}>{questions[currentIndex]}</Text>
      <TextInput
        style={styles.input}
        value={answer}
        onChangeText={setAnswer}
        placeholder="Your answer..."
        placeholderTextColor="#666"
        multiline
        autoFocus
      />
      <View style={styles.actions}>
        <TouchableOpacity onPress={onCancel}>
          <Text style={styles.cancelText}>Cancel</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.nextButton} onPress={handleNext}>
          <Text style={styles.nextText}>{isLast ? "Generate Podcast" : "Next"}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 24 },
  progress: { fontSize: 14, color: "#888", marginBottom: 16 },
  question: { fontSize: 20, fontWeight: "600", color: "#fff", marginBottom: 24, lineHeight: 28 },
  input: {
    backgroundColor: "#1a1a1a", borderRadius: 12, padding: 16,
    color: "#fff", fontSize: 16, minHeight: 80, textAlignVertical: "top",
    borderWidth: 1, borderColor: "#333",
  },
  actions: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 24 },
  cancelText: { color: "#888", fontSize: 16 },
  nextButton: { backgroundColor: "#6366f1", borderRadius: 12, paddingHorizontal: 24, paddingVertical: 12 },
  nextText: { color: "#fff", fontSize: 16, fontWeight: "600" },
});
